const STATE_KEY='weekly_intelligence_state_v1';
const PREF_KEY='weekly_intelligence_prefs_v1';
let data={meta:{},articles:[]}, status={};
let state=JSON.parse(localStorage.getItem(STATE_KEY)||'{}');
let prefs=JSON.parse(localStorage.getItem(PREF_KEY)||'{"sources":{},"tags":{}}');
const $=id=>document.getElementById(id);
const effects={accurate:{s:.12,t:.10},more:{s:.28,t:.34},bad:{s:-.18,t:-.16},less:{s:-.32,t:-.38}};
function save(){localStorage.setItem(STATE_KEY,JSON.stringify(state));localStorage.setItem(PREF_KEY,JSON.stringify(prefs));}
function st(id){return state[id]||{status:'new',feedback:null};}
function score(a){let x=Number(a.reading_score??a.base_score??5)+(prefs.sources[a.source]||0);(a.tags||[]).forEach(t=>x+=prefs.tags[t]||0);return Math.max(0,Math.min(10,x));}
function grade(x){return x>=8.7?'S':x>=7.2?'A':x>=5.5?'B':'C';}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function short(s){return s.length>28?s.slice(0,27)+'…':s;}
function fmt(s){return s?s.slice(0,10).replaceAll('-','/'):'日期不明';}
function label(s){return ({new:'未处理',later:'稍后看',read:'已读',save:'进 Notion',skip:'跳过'})[s]||s;}
function btn(text,active,fn){const b=document.createElement('button');b.type='button';b.className='btn'+(active?' active':'');b.textContent=text;b.onclick=fn;return b;}
function feedback(a,v){const cur=st(a.id);if(cur.feedback&&effects[cur.feedback]){const e=effects[cur.feedback];prefs.sources[a.source]=(prefs.sources[a.source]||0)-e.s;(a.tags||[]).forEach(t=>prefs.tags[t]=(prefs.tags[t]||0)-e.t);}cur.feedback=cur.feedback===v?null:v;if(cur.feedback){const e=effects[cur.feedback];prefs.sources[a.source]=(prefs.sources[a.source]||0)+e.s;(a.tags||[]).forEach(t=>prefs.tags[t]=(prefs.tags[t]||0)+e.t);}state[a.id]=cur;save();render();}
function setStatus(a,v){const cur=st(a.id);cur.status=cur.status===v?'new':v;state[a.id]=cur;save();render();}
function renderMetrics(){const arts=data.articles||[],gs=arts.map(a=>grade(score(a)));const vals=[['新增',status.raw_new_count??arts.length,'8/10 起'],['去重后',status.deduped_count??arts.length,'唯一文章'],['深读',status.deep_read_count??0,'高潜力候选'],['S',gs.filter(x=>x==='S').length,'必看'],['A',gs.filter(x=>x==='A').length,'值得看'],['待处理',arts.filter(a=>st(a.id).status==='new').length,'未反馈']];$('metrics').innerHTML=vals.map(v=>`<div class="metric"><div class="metric-label">${v[0]}</div><div class="metric-value">${v[1]}</div><div class="metric-sub">${v[2]}</div></div>`).join('');}
function renderCoverage(){const exp=status.expected_sources??21,ok=status.successful_sources??0;$('coveragePill').textContent=`${ok}/${exp}`;const failed=status.failed_sources||[];const w=$('coverageWarning');if(!status.generated_at){w.classList.remove('hidden');w.textContent='首次数据刷新尚未运行。请在 GitHub Actions 手动运行一次 Update feeds。';}else if(failed.length){w.classList.remove('hidden');w.textContent=`⚠ 本次并非全量：${failed.length} 个来源抓取失败。`; }else w.classList.add('hidden');$('sourceCoverage').innerHTML=(status.sources||[]).map(s=>`<div class="coverage-item"><span title="${esc(s.error||'')}">${esc(short(s.name))}</span><span class="${s.status==='ok'?'status-ok':s.status==='failed'?'status-fail':'status-pending'}">${s.status==='ok'?(s.new_count||0)+' 新增':s.status==='failed'?'失败':'待刷新'}</span></div>`).join('');}
function renderPrefs(){let rows=[];Object.entries(prefs.tags).filter(([,v])=>Math.abs(v)>.04).forEach(([k,v])=>rows.push(['# '+k,v]));Object.entries(prefs.sources).filter(([,v])=>Math.abs(v)>.04).forEach(([k,v])=>rows.push([short(k),v]));rows.sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));$('learnedPrefs').innerHTML=rows.length?rows.slice(0,10).map(r=>`<div class="pref-row"><span>${esc(r[0])}</span><span class="weight ${r[1]>=0?'pos':'neg'}">${r[1]>=0?'+':''}${r[1].toFixed(2)}</span></div>`).join(''):'<div class="muted small">还没有反馈。点击文章下方按钮后，这里会出现偏好。</div>';}
function sourceOptions(){const sel=$('sourceFilter'),cur=sel.value,arr=[...new Set((data.articles||[]).map(a=>a.source))].sort();sel.innerHTML='<option value="all">全部来源</option>'+arr.map(s=>`<option value="${esc(s)}">${esc(short(s))}</option>`).join('');if(arr.includes(cur))sel.value=cur;}
function visible(a){const g=grade(score(a)),gf=$('gradeFilter').value,sf=$('statusFilter').value,src=$('sourceFilter').value,as=st(a.id).status;if(gf==='SA'&&!['S','A'].includes(g))return false;if(['S','A','B'].includes(gf)&&g!==gf)return false;if(sf==='active'&&as==='skip')return false;if(!['all','active'].includes(sf)&&as!==sf)return false;if(src!=='all'&&a.source!==src)return false;return true;}
function renderArticles(){let arts=(data.articles||[]).filter(visible);if($('personalizedSort').checked)arts.sort((a,b)=>score(b)-score(a));$('visibleCount').textContent=`${arts.length} 篇`;$('emptyState').classList.toggle('hidden',arts.length>0);$('articleList').innerHTML='';for(const a of arts){const cur=st(a.id),sc=score(a),g=grade(sc),el=document.createElement('article');el.className='article';el.innerHTML=`<div class="article-top"><div class="meta"><span class="grade grade-${g}">${g}</span><span class="muted small">${fmt(a.published)} · ${esc(a.source)}</span><span class="pill">${label(cur.status)}</span></div><div class="muted small">个人分 ${sc.toFixed(1)}</div></div><a class="article-title" target="_blank" rel="noopener noreferrer" href="${esc(a.url)}">${esc(a.title)}</a><div class="scores"><span class="score">阅读价值 <b>${Number(a.reading_score??5).toFixed(1)}</b>/10</span><span class="score">Notion价值 <b>${Number(a.notion_score??4).toFixed(1)}</b>/10</span><span class="score">${a.content_checked?'正文已检查':'标题/摘要判断'}</span></div><div class="why"><b>为什么选：</b>${esc(a.reason||'等待筛选说明')}</div><div class="tags">${(a.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>${a.screening_note?`<div class="source-note">${esc(a.screening_note)}</div>`:''}`;const c=document.createElement('div');c.className='controls';[['later','稍后看'],['read','已读'],['save','进 Notion'],['skip','跳过']].forEach(([v,t])=>c.appendChild(btn(t,cur.status===v,()=>setStatus(a,v))));const lab=document.createElement('div');lab.className='feedback-label';lab.textContent='筛选反馈（用于学习）';c.appendChild(lab);[['accurate','👍 选得准'],['more','⭐ 多推类似'],['bad','👎 不值得'],['less','🚫 少推此类']].forEach(([v,t])=>c.appendChild(btn(t,cur.feedback===v,()=>feedback(a,v))));el.appendChild(c);$('articleList').appendChild(el);}}
function render(){renderMetrics();renderCoverage();renderPrefs();sourceOptions();renderArticles();}
async function init(){try{[data,status]=await Promise.all([fetch('data/articles.json',{cache:'no-store'}).then(r=>r.json()),fetch('data/source_status.json',{cache:'no-store'}).then(r=>r.json())]);$('lastUpdated').textContent=data.meta?.generated_at?`最近更新 ${new Date(data.meta.generated_at).toLocaleString('ja-JP')}`:'尚未首次刷新';render();}catch(e){$('coverageWarning').classList.remove('hidden');$('coverageWarning').textContent='无法读取数据文件：'+e.message;}}
['gradeFilter','statusFilter','sourceFilter','personalizedSort'].forEach(id=>$(id).addEventListener('change',renderArticles));$('resetLearning').addEventListener('click',()=>{if(confirm('确定清空本浏览器的学习权重和文章处理状态？')){state={};prefs={sources:{},tags:{}};save();render();}});init();