let IK={}, IW={meta:{},articles:[]};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));

const RULES=[
['Agentic Commerce',/エージェンティック|agentic/i],['AI Search / AEO',/AEO|AIO|GEO|AI検索|AI経由|AI型購買|AIショッピング/i],['生成AI実務',/生成AI|ChatGPT|LLM|AI活用|AIエージェント/i],['CEP / 想起',/CEP|想起|第一想起/i],['KPI / 計測',/KPI|KGI|計測|指標|効果測定/i],['検索行動',/検索行動|検索数|検索クエリ|SCM|SEO/i],['購買行動',/購買|購入|買う|ファネル|決済/i],['消費者インサイト',/消費者|生活者|インサイト|N.?=.?1|顧客理解/i],['EC成長',/EC|eコマース|Amazon|楽天|TikTok Shop|D2C|モール/i],['広告効果',/広告|メディア投資|リーチ|フリークエンシー|CTR|CPA/i],['ブランド成長',/ブランド|認知|シェア|ロイヤル|浸透率/i],['価格戦略',/価格|値上げ|プライシング|値付け/i],['CRM / LTV',/CRM|LTV|会員|ロイヤルティ|メール|メルマガ/i],['SNS / UGC',/SNS|UGC|TikTok|Instagram|インフルエンサー|VTuber/i],['市場 / 競合',/市場|競合|差別化|シェア|ポジショニング/i],['調査設計',/調査|アンケート|モニター|サンプル|回答率/i],['商品開発',/商品開発|新商品|新ニーズ|パッケージ/i],['マネジメント',/マネジメント|組織|会議|評価制度|コミュニケーション/i]
];
const STOP=new Set(['について','による','ため','とは','から','まで','する','した','して','いる','ある','ない','これ','それ','マーケティング','最新','公開','解説','ポイント','方法','実践','記事','日経クロストレンド','markezine']);
function ks(){return IK.items||IK.recent_stock||[];}
function ctext(k){return (k.comments||[]).map(c=>c.text||'').join(' ');}
function ktext(k){return `${k.title||''} ${k.summary||''} ${ctext(k)}`;}
function topics(text){return RULES.filter(([,re])=>re.test(text||'')).map(([n])=>n);}
function topicCounts(rows){const c={};rows.forEach(x=>topics(typeof x==='string'?x:ktext(x)).forEach(t=>c[t]=(c[t]||0)+1));return c;}
function words(text){const raw=(text||'').toLowerCase().match(/[a-z0-9][a-z0-9+._-]{1,}|[一-龯ぁ-んァ-ヶー]{2,12}/g)||[];return [...new Set(raw.filter(x=>!STOP.has(x)&&x.length>1))].slice(0,90);}
function relatedScore(a,k){const at=`${a.title||''} ${a.summary||''} ${a.reason||''} ${(a.concepts||[]).join(' ')}`,kt=ktext(k);let s=0;const ac=new Set(topics(at)),kc=new Set(topics(kt));ac.forEach(x=>{if(kc.has(x))s+=2.4});const aw=new Set(words(a.title||'')),kw=new Set(words(k.title||''));aw.forEach(x=>{if(kw.has(x))s+=x.length>=5?1.2:.65});const allA=new Set(words(at)),allK=new Set(words(kt));let n=0;allA.forEach(x=>{if(allK.has(x))n++});s+=Math.min(n,5)*.2;return s;}
function related(a,n=3){return ks().map(k=>({k,s:relatedScore(a,k)})).filter(x=>x.s>=1.7).sort((a,b)=>b.s-a.s).slice(0,n);}
function rankHtml(rows,max=8){const top=rows.slice(0,max),mx=Math.max(...top.map(x=>x[1]),1);return top.map(([name,count],i)=>`<div class="rank-row"><span class="rank-index">${String(i+1).padStart(2,'0')}</span><div class="rank-main"><div class="rank-head"><span>${esc(name)}</span><b>${count}</b></div><div class="bar-track"><div class="bar-fill" style="width:${count/mx*100}%"></div></div></div></div>`).join('')||'<div class="muted small">暂无数据</div>';}

function renderMetrics(){const items=ks(),cs=items.reduce((n,k)=>n+(k.comments||[]).length,0),withC=items.filter(k=>(k.comments||[]).length).length;const weekly=IW.articles||[],connected=weekly.filter(a=>related(a,1).length).length;const vals=[['Stock',IK.metrics?.stock??items.length,'知识库'],['Comment',cs,`${withC}篇含笔记`],['主题',Object.keys(topicCounts(items)).length,'细分主题'],['本周关联',connected,`/${weekly.length||0}篇可连旧知识`],['近90天',IK.metrics?.added_90d??0,'新增'],['分类',(IK.categories||[]).filter(x=>x.stock>0).length,'Notion種類']];$('insightMetrics').innerHTML=vals.map(v=>`<div class="metric"><div class="metric-label">${v[0]}</div><div class="metric-value">${v[1]}</div><div class="metric-sub">${v[2]}</div></div>`).join('');}
function renderLongTerm(){const c=Object.entries(topicCounts(ks())).sort((a,b)=>b[1]-a[1]);$('longTermTopics').innerHTML=rankHtml(c);}
function renderShift(){const cutoff=new Date(Date.now()-90*86400000),recent=ks().filter(k=>k.date&&new Date(k.date)>=cutoff),allC=topicCounts(ks()),rC=topicCounts(recent);const rows=Object.entries(rC).map(([t,n])=>[t,n, n/Math.max(1,recent.length)-((allC[t]||0)/Math.max(1,ks().length))]).sort((a,b)=>b[2]-a[2]);$('recentShift').innerHTML=rows.slice(0,8).map(([t,n,d],i)=>`<div class="shift-row"><span class="rank-index">${String(i+1).padStart(2,'0')}</span><div><b>${esc(t)}</b><div class="muted small">近90天 ${n}篇 · 相对长期 ${d>=0?'+':''}${(d*100).toFixed(1)}pt</div></div></div>`).join('')||'<div class="muted small">近90天暂无足够数据</div>';}
function weeklyGrade(a){const x=Number(a.reading_score??a.base_score??5);return x>=8.7?'S':x>=7.2?'A':x>=5.5?'B':'C';}
function renderWeeklyConnections(){let arts=(IW.articles||[]).filter(a=>['S','A'].includes(weeklyGrade(a))).sort((a,b)=>(b.reading_score||0)-(a.reading_score||0)).slice(0,8);$('weeklyConnections').innerHTML=arts.map(a=>{const rs=related(a,3);return `<div class="connection-item"><div class="connection-title"><span class="grade grade-${weeklyGrade(a)}">${weeklyGrade(a)}</span><a href="${esc(a.url)}" target="_blank" rel="noopener noreferrer">${esc(a.title)}</a></div>${rs.length?`<div class="connection-related">${rs.map(({k})=>`<a href="${esc(k.url)}" target="_blank" rel="noopener noreferrer">↳ ${esc(k.title)}</a>`).join('')}</div>`:'<div class="muted small">目前没有明显旧知识连接</div>'}</div>`}).join('')||'<div class="muted small">本周暂无 S/A 候选</div>';}
function renderGaps(){const all=topicCounts(ks()),weekly={};(IW.articles||[]).forEach(a=>topics(`${a.title||''} ${a.summary||''} ${a.reason||''}`).forEach(t=>weekly[t]=(weekly[t]||0)+1));const rows=Object.entries(weekly).map(([t,n])=>({t,n,stock:all[t]||0})).filter(x=>x.n>=1).sort((a,b)=>(a.stock-b.stock)||(b.n-a.n)).slice(0,6);const catGaps=(IK.categories||[]).filter(x=>x.total>=8&&x.stock/x.total<.3).sort((a,b)=>a.stock/a.total-b.stock/b.total).slice(0,3);const html=[];rows.forEach(x=>html.push(`<div class="insight-item">本周出现 <b>${esc(x.t)}</b> ${x.n}次，但知识库只有 ${x.stock}篇相关 Stock。</div>`));catGaps.forEach(x=>html.push(`<div class="insight-item"><b>${esc(x.name)}</b> 大类保存率仅 ${Math.round(x.stock/x.total*100)}%，可观察这是主动淘汰还是知识空白。</div>`));$('knowledgeGaps').innerHTML=html.join('')||'<div class="muted small">暂未发现明显空白</div>';}
function renderReview(){const topTopics=new Set(Object.entries(topicCounts(ks())).sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>x[0]));let rows=ks().map(k=>{const age=k.date?(Date.now()-new Date(k.date))/86400000:0;const t=topics(ktext(k));let s=Math.min(age/365,3)+(k.comments||[]).length*.8+t.filter(x=>topTopics.has(x)).length*.5;return {k,s}}).filter(x=>x.s>1).sort((a,b)=>b.s-a.s).slice(0,10);$('reviewCandidates').innerHTML=rows.map(({k})=>`<article class="article"><div class="article-top"><div class="meta"><span class="pill">${esc(k.category||'未分类')}</span><span class="muted small">${esc(k.date||'')}</span>${(k.comments||[]).length?`<span class="pill">💬 ${(k.comments||[]).length}</span>`:''}</div></div><a class="article-title" href="${esc(k.url)}" target="_blank" rel="noopener noreferrer">${esc(k.title)}</a><div class="tags">${topics(ktext(k)).slice(0,5).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></article>`).join('');}
function renderCommentConcepts(){const c={};ks().filter(k=>(k.comments||[]).length).forEach(k=>topics(ctext(k)).forEach(t=>c[t]=(c[t]||0)+1));$('commentConcepts').innerHTML=Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([t,n])=>`<span class="topic-pill">${esc(t)} <b>${n}</b></span>`).join('')||'<span class="muted small">自动同步后会统计 Comment 主题</span>';}
function renderHealth(){const items=ks(),withSummary=items.filter(k=>k.summary).length,withComments=items.filter(k=>(k.comments||[]).length).length,uncat=items.filter(k=>(k.category||'未分类')==='未分类').length,dups={};items.forEach(k=>dups[k.title]=(dups[k.title]||0)+1);const dupCount=Object.values(dups).filter(n=>n>1).length;const vals=[`<div class="insight-item">有 summary：<b>${withSummary}/${items.length}</b></div>`,`<div class="insight-item">有 Comment：<b>${withComments}/${items.length}</b></div>`,`<div class="insight-item">未分类 Stock：<b>${uncat}</b></div>`,`<div class="insight-item">重复标题组：<b>${dupCount}</b>（后续可做合并提醒）</div>`];$('knowledgeHealth').innerHTML=vals.join('');}
async function init(){try{[IK,IW]=await Promise.all([fetch('data/knowledge.json',{cache:'no-store'}).then(r=>r.json()),fetch('data/articles.json',{cache:'no-store'}).then(r=>r.json()).catch(()=>({articles:[]}))]);$('insightsUpdated').textContent=IK.meta?.snapshot_at?`知识库 ${new Date(IK.meta.snapshot_at).toLocaleString('ja-JP')}`:'知识库快照';renderMetrics();renderLongTerm();renderShift();renderWeeklyConnections();renderGaps();renderReview();renderCommentConcepts();renderHealth();}catch(e){$('insightsUpdated').textContent='数据读取失败';console.error(e);}}
init();
