let K={};
let activeKnowledgeCategory='all',activeTopic='all',knowledgeLimit=30;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const TOPIC_RULES=[['Agentic Commerce',/エージェンティック|agentic/i],['AI Search / AEO',/AEO|AIO|GEO|AI検索|AI経由|AI型購買|AIショッピング/i],['生成AI実務',/生成AI|ChatGPT|LLM|AI活用|AIエージェント/i],['CEP / 想起',/CEP|想起|第一想起/i],['KPI / 計測',/KPI|KGI|計測|指標|効果測定/i],['検索行動',/検索行動|検索数|検索クエリ|SCM|SEO/i],['購買行動',/購買|購入|買う|ファネル|決済/i],['消費者インサイト',/消費者|生活者|インサイト|N.?=.?1|顧客理解/i],['EC成長',/EC|eコマース|Amazon|楽天|TikTok Shop|D2C|モール/i],['広告効果',/広告|メディア投資|リーチ|フリークエンシー|CTR|CPA/i],['ブランド成長',/ブランド|認知|シェア|ロイヤル|浸透率/i],['価格戦略',/価格|値上げ|プライシング|値付け/i],['CRM / LTV',/CRM|LTV|会員|ロイヤルティ|メール|メルマガ/i],['SNS / UGC',/SNS|UGC|TikTok|Instagram|インフルエンサー|VTuber/i],['市場 / 競合',/市場|競合|差別化|シェア|ポジショニング/i],['調査設計',/調査|アンケート|モニター|サンプル|回答率/i],['商品開発',/商品開発|新商品|新ニーズ|パッケージ/i],['マネジメント',/マネジメント|組織|会議|評価制度|コミュニケーション/i]];
function items(){return K.items||K.recent_stock||[]}
function commentsOf(a){return Array.isArray(a.comments)?a.comments:[]}
function textOf(a){return `${a.title||''} ${a.summary||''} ${a.page_body||''} ${commentsOf(a).map(c=>c.text||'').join(' ')}`}
function topicsFor(a){if(Array.isArray(a.topics)&&a.topics.length)return a.topics;const text=textOf(a),out=[];TOPIC_RULES.forEach(([n,re])=>{if(re.test(text))out.push(n)});return out}
function bodyHtml(text){if(!text)return '<p class="muted">这个 Notion 页面没有可读取的正文 block。</p>';return String(text).split(/\n+/).filter(Boolean).map(line=>{const s=esc(line);if(line.startsWith('### '))return `<h4>${esc(line.slice(4))}</h4>`;if(line.startsWith('## '))return `<h3>${esc(line.slice(3))}</h3>`;if(line.startsWith('# '))return `<h2>${esc(line.slice(2))}</h2>`;if(line.startsWith('• '))return `<div class="notion-bullet">• ${esc(line.slice(2))}</div>`;if(line.startsWith('> '))return `<blockquote>${esc(line.slice(2))}</blockquote>`;return `<p>${s}</p>`}).join('')}
function categoryRows(){const rows=[...(K.categories||[])].filter(x=>x.stock>0).sort((a,b)=>b.stock-a.stock);if(!rows.length){const c={};items().forEach(a=>c[a.category||'未分类']=(c[a.category||'未分类']||0)+1);return Object.entries(c).map(([name,stock])=>({name,stock,total:stock,rejected:0})).sort((a,b)=>b.stock-a.stock)}return rows}
function jumpToResults(){const el=$('knowledgeFilterContext');$('knowledgeResultsAnchor')?.scrollIntoView({behavior:'smooth',block:'start'});if(el){el.classList.remove('focus-flash');requestAnimationFrame(()=>el.classList.add('focus-flash'));setTimeout(()=>el.classList.remove('focus-flash'),900)}}
function setCategory(cat,doJump=true){activeKnowledgeCategory=cat;activeTopic='all';knowledgeLimit=30;renderCategoryTags();renderTopics();renderList();if(doJump)jumpToResults()}
function renderMetrics(){const m=K.metrics||{},stock=m.stock??items().length,total=m.total??stock,cc=items().reduce((n,a)=>n+commentsOf(a).length,0),wc=items().filter(a=>commentsOf(a).length).length;const vals=[['Stock',stock,`${total?Math.round(stock/total*100):0}% 保存率`],['Comment',cc,`${wc} 篇含笔记`],['分类',categoryRows().length,'Notion 種類'],['细分主题',new Set(items().flatMap(topicsFor)).size,'正文+Comment'],['近90天',m.added_90d??0,'新增条目'],['知识总量',total,'含淘汰/未保存']];$('knowledgeMetrics').innerHTML=vals.map(v=>`<div class="metric"><div class="metric-label">${v[0]}</div><div class="metric-value">${v[1]}</div><div class="metric-sub">${v[2]}</div></div>`).join('')}
function renderCategoryTags(){const rows=categoryRows(),all=K.metrics?.stock??items().length;$('knowledgeCategoryTags').innerHTML=[{name:'all',stock:all},...rows].map(x=>`<button type="button" class="category-filter-btn ${activeKnowledgeCategory===x.name?'active':''}" data-cat="${esc(x.name)}"><span>${x.name==='all'?'全部':esc(x.name)}</span><b>${x.stock}</b></button>`).join('');$('knowledgeCategoryTags').querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>setCategory(b.dataset.cat,true))}
function renderCategories(){const rows=categoryRows().filter(x=>x.name!=='未分类'),max=Math.max(...rows.map(x=>x.stock),1);$('categoryBars').innerHTML=rows.map(x=>`<button class="category-row category-row-button ${activeKnowledgeCategory===x.name?'selected':''}" type="button" data-catbar="${esc(x.name)}"><div class="category-row-head"><span>${esc(x.name)}</span><span class="muted small">Stock ${x.stock}/${x.total} · ${x.total?Math.round(x.stock/x.total*100):0}%</span></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,x.stock/max*100)}%"></div></div></button>`).join('');$('categoryBars').querySelectorAll('[data-catbar]').forEach(b=>b.onclick=()=>setCategory(b.dataset.catbar,true))}
function renderTopics(){const c={};items().forEach(a=>topicsFor(a).forEach(t=>c[t]=(c[t]||0)+1));const rows=Object.entries(c).sort((a,b)=>b[1]-a[1]);$('topicCloud').innerHTML=`<button type="button" class="topic-pill ${activeTopic==='all'?'active':''}" data-topic="all">全部主题</button>`+rows.map(([t,n])=>`<button type="button" class="topic-pill ${activeTopic===t?'active':''}" data-topic="${esc(t)}">${esc(t)} <b>${n}</b></button>`).join('');$('topicCloud').querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{activeTopic=b.dataset.topic;knowledgeLimit=30;renderTopics();renderList();jumpToResults()})}
function currentRows(){const q=($('knowledgeSearch')?.value||'').trim().toLowerCase(),cf=$('knowledgeCommentFilter')?.value||'all',sort=$('knowledgeSort')?.value||'newest';let rows=items().filter(a=>{if(activeKnowledgeCategory!=='all'&&(a.category||'未分类')!==activeKnowledgeCategory)return false;if(activeTopic!=='all'&&!topicsFor(a).includes(activeTopic))return false;if(cf==='with'&&!commentsOf(a).length)return false;if(cf==='without'&&commentsOf(a).length)return false;if(q&&!textOf(a).toLowerCase().includes(q)&&!topicsFor(a).join(' ').toLowerCase().includes(q))return false;return true});if(sort==='oldest')rows.sort((a,b)=>(a.date||'').localeCompare(b.date||''));else if(sort==='comments')rows.sort((a,b)=>commentsOf(b).length-commentsOf(a).length||(b.date||'').localeCompare(a.date||''));else rows.sort((a,b)=>(b.date||'').localeCompare(a.date||''));return rows}
function commentsHtml(a){const cs=commentsOf(a);if(!cs.length)return '<div class="notion-comments empty-comments">没有可读取的页面 Comment</div>';return `<section class="notion-comments"><div class="reader-section-title">💬 你的 Comment · ${cs.length}</div>${cs.map(c=>`<div class="comment-item"><div>${esc(c.text||'')}</div>${c.created_time?`<small>${esc(String(c.created_time).slice(0,10))}</small>`:''}</div>`).join('')}</section>`}
function commentPreview(a){const cs=commentsOf(a);if(!cs.length)return '';const t=cs[0].text||'';return `<div class="comment-preview"><span>💬</span><span>${esc(t.length>140?t.slice(0,140)+'…':t)}</span>${cs.length>1?`<b>+${cs.length-1}</b>`:''}</div>`}
function renderList(){const rows=currentRows(),shown=rows.slice(0,knowledgeLimit),label=activeKnowledgeCategory==='all'?(activeTopic==='all'?'全部分类':`主题：${activeTopic}`):activeKnowledgeCategory;$('knowledgeCount').textContent=`${rows.length} 篇`;$('knowledgeActiveCategory').textContent=label;$('knowledgeFilterLabel').textContent=label;$('knowledgeFilterCount').textContent=`${rows.length} 篇`;$('clearKnowledgeFilter').classList.toggle('hidden',activeKnowledgeCategory==='all'&&activeTopic==='all');$('knowledgeList').innerHTML=shown.map((a,i)=>`<article class="article knowledge-article"><div class="knowledge-index">${String(i+1).padStart(2,'0')}</div><div class="article-top"><div class="meta"><span class="pill">${esc(a.category||'未分类')}</span><span class="muted small">${esc(a.date||'')}</span>${commentsOf(a).length?`<span class="pill comment-pill">💬 ${commentsOf(a).length}</span>`:''}</div><span class="muted small">Notion Stock</span></div><details class="knowledge-reader"><summary class="article-title knowledge-title-button">${esc(a.title)}</summary>${a.summary?`<div class="knowledge-summary"><b>Summary</b><br>${esc(a.summary)}</div>`:''}<div class="tags">${topicsFor(a).slice(0,5).map(t=>`<button type="button" class="tag tag-button" data-inline-topic="${esc(t)}">${esc(t)}</button>`).join('')}</div>${commentPreview(a)}<div class="notion-reader-panel"><div class="reader-toolbar"><span>Notion 页面内容</span><a href="${esc(a.url)}" target="_blank" rel="noopener noreferrer">↗ 打开 Notion</a></div><div class="notion-body">${bodyHtml(a.page_body)}</div>${commentsHtml(a)}</div></details></article>`).join('')||'<div class="empty"><h3>没有匹配内容</h3><p>搜索会检查标题、summary、Notion正文和你的 Comment。</p></div>';$('knowledgeList').querySelectorAll('[data-inline-topic]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();activeTopic=b.dataset.inlineTopic;knowledgeLimit=30;renderTopics();renderList();jumpToResults()});const more=$('loadMoreKnowledge');if(more){more.classList.toggle('hidden',shown.length>=rows.length);more.textContent=`再显示 ${Math.min(30,Math.max(0,rows.length-shown.length))} 篇`}}
function renderResurface(){let rows=items().filter(a=>a.date&&new Date(a.date)<new Date(Date.now()-365*86400000));if(rows.length<3)rows=[...items()];rows.sort(()=>Math.random()-.5);rows=rows.slice(0,5);$('resurfaceList').innerHTML=rows.map((a,i)=>`<button class="resurface-item resurface-button" type="button" data-resurface="${esc(a.id||'')}"><span class="resurface-num">${String(i+1).padStart(2,'0')}</span><span><b>${esc(a.title)}</b><small>${esc(a.category||'未分类')} · ${esc(a.date||'')}</small></span></button>`).join('');$('resurfaceList').querySelectorAll('[data-resurface]').forEach(b=>b.onclick=()=>{const a=items().find(x=>x.id===b.dataset.resurface);if(!a)return;setCategory(a.category||'未分类',true);setTimeout(()=>{const card=[...document.querySelectorAll('.knowledge-article')].find(x=>x.textContent.includes(a.title));const d=card?.querySelector('details');if(d){d.open=true;card.scrollIntoView({behavior:'smooth',block:'center'})}},350)})}
function renderInsights(){const c=K.categories||[],byRate=[...c].filter(x=>x.name!=='未分类'&&x.total>=5).map(x=>({...x,rate:x.stock/x.total})).sort((a,b)=>b.rate-a.rate),top=byRate[0],tc={};items().forEach(a=>topicsFor(a).forEach(t=>tc[t]=(tc[t]||0)+1));const strongest=Object.entries(tc).sort((a,b)=>b[1]-a[1])[0],list=[];if(top)list.push(`<div class="insight-item"><b>${esc(top.name)}</b> 保存率 ${Math.round(top.rate*100)}%</div>`);if(strongest)list.push(`<div class="insight-item">最密集细分主题：<b>${esc(strongest[0])}</b>（${strongest[1]}篇）</div>`);list.push('<div class="insight-item">站内搜索、主题识别与旧知识关联现在都会使用 <b>Notion正文 + Comment</b>。</div>');$('knowledgeInsights').innerHTML=list.join('')}
async function init(){try{K=await fetch('data/knowledge.json',{cache:'no-store'}).then(r=>r.json());const snap=K.meta?.snapshot_at;$('knowledgeUpdated').textContent=snap?`Notion同步 ${new Date(snap).toLocaleString('ja-JP')}`:'Notion快照';renderMetrics();renderCategoryTags();renderCategories();renderTopics();renderList();renderResurface();renderInsights()}catch(e){$('knowledgeUpdated').textContent='数据读取失败';console.error(e)}}
$('knowledgeSearch')?.addEventListener('input',()=>{knowledgeLimit=30;renderList()});$('knowledgeCommentFilter')?.addEventListener('change',()=>{knowledgeLimit=30;renderList()});$('knowledgeSort')?.addEventListener('change',renderList);$('loadMoreKnowledge')?.addEventListener('click',()=>{knowledgeLimit+=30;renderList()});$('shuffleResurface')?.addEventListener('click',renderResurface);$('clearKnowledgeFilter')?.addEventListener('click',()=>setCategory('all',true));init();
