let WS=null,WK=null,activeDomain='all';
const $w=id=>document.getElementById(id);
const ew=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function noteMap(){const m=new Map();(WS?.notes||[]).forEach(n=>m.set(n.id,n));return m;}
function ruleText(r){return `${r.title||''} ${r.principle||''} ${r.when||''} ${(r.steps||[]).join(' ')} ${(r.metrics||[]).join(' ')} ${(r.traps||[]).join(' ')} ${r.detail||''}`;}
function noteText(n){return `${n.title||''} ${n.text||''} ${(n.domains||[]).map(d=>d.name).join(' ')}`;}
function notionText(a){return `${a.title||''} ${a.summary||''} ${a.page_body||''} ${(a.comments||[]).map(c=>c.text||'').join(' ')} ${(a.topics||[]).join(' ')}`;}
function tokens(text){return [...new Set((String(text||'').match(/[A-Za-z][A-Za-z0-9+./-]{2,}|[一-龯ぁ-んァ-ヶ]{2,12}/g)||[]).map(x=>x.toLowerCase()).filter(x=>!['什么','怎么','这个','ため','こと','する','ある','いる','ます','です','これ','その','から','より','など','the','and','with'].includes(x)))].slice(0,80);}
function notionEvidence(r){if(!WK||WK.locked)return[];const ts=tokens(ruleText(r));return (WK.items||[]).map(a=>{const low=notionText(a).toLowerCase();let score=0,hits=[];ts.forEach(t=>{if(low.includes(t)){score+=t.length>4?2:1;hits.push(t)}});return {a,score,hits};}).filter(x=>x.score>=3).sort((a,b)=>b.score-a.score).slice(0,5);}
function sources(){return WS?.sources||[];}
function domains(){const c={};(WS?.notes||[]).forEach(n=>(n.domains||[]).slice(0,1).forEach(d=>c[d.name]=(c[d.name]||0)+1));return Object.entries(c).sort((a,b)=>b[1]-a[1]);}
function ruleDomain(r){return r.domain||(r.domains?.[0]?.name)||'其他';}
function allRules(){if((WS?.rules||[]).length)return WS.rules;return (WS?.candidate_principles||[]).map(x=>({...x,principle:x.detail,when:'来自你的经验/读书笔记，作为待验证规则。',steps:[],metrics:[],traps:[],confidence:'medium'}));}
function renderMetrics(){const vals=[['工作体系规则',allRules().length,WS?.rules?.length?'已综合':'候选规则'],['私人笔记',(WS?.notes||[]).length,'Google 3个来源'],['Notion Stock',(WK?.items||[]).length,'外部证据'],['知识领域',domains().length,'自动归类']];$w('workSystemMetrics').innerHTML=vals.map(v=>`<div class="metric"><div class="metric-label">${v[0]}</div><div class="metric-value">${v[1]}</div><div class="metric-sub">${v[2]}</div></div>`).join('');}
function renderSources(){const labels={experience:'工作经验',book:'读书笔记',field_manual:'EC/Amazon实战'};const cards=sources().map(s=>`<div class="source-layer"><b>${ew(labels[s.kind]||s.label||s.name)}</b><span>${ew(s.name||s.label||'')}</span><small>${s.modifiedTime?`更新 ${ew(String(s.modifiedTime).slice(0,10))}`:'等待首次同步'}</small></div>`);cards.push(`<div class="source-layer"><b>Notion Knowledge</b><span>外部文章、正文、Comment</span><small>${WK?.meta?.snapshot_at?`更新 ${ew(String(WK.meta.snapshot_at).slice(0,10))}`:'未解锁'}</small></div>`);$w('workSystemSources').innerHTML=cards.join('');}
function renderChips(){const ds=domains();$w('scenarioChips').innerHTML=`<button class="scenario-chip ${activeDomain==='all'?'active':''}" data-domain="all">全部</button>`+ds.map(([d,n])=>`<button class="scenario-chip ${activeDomain===d?'active':''}" data-domain="${ew(d)}">${ew(d)} · ${n}</button>`).join('');$w('scenarioChips').querySelectorAll('[data-domain]').forEach(b=>b.onclick=()=>{activeDomain=b.dataset.domain;renderChips();renderRules();});}
function sourceEvidence(r){const m=noteMap();return (r.evidence_ids||[]).map(id=>m.get(id)).filter(Boolean).slice(0,8);}
function arrayBlock(label,arr){if(!arr?.length)return'';return `<div class="playbook-col"><div class="playbook-label">${label}</div><ul>${arr.map(x=>`<li>${ew(x)}</li>`).join('')}</ul></div>`;}
function renderRules(){const q=($w('playbookSearch')?.value||'').trim().toLowerCase();let rows=allRules().filter(r=>(activeDomain==='all'||ruleDomain(r)===activeDomain)&&(!q||ruleText(r).toLowerCase().includes(q)||sourceEvidence(r).some(n=>noteText(n).toLowerCase().includes(q))));$w('playbookList').innerHTML=rows.map((r,i)=>{const se=sourceEvidence(r),ne=notionEvidence(r);return `<article class="card playbook-card"><div class="playbook-card-head"><div><div class="playbook-label">${ew(ruleDomain(r))} · ${ew(r.confidence||'candidate')}</div><h2><span class="playbook-num">${String(i+1).padStart(2,'0')}</span>${ew(r.title)}</h2></div><span class="evidence-count">${se.length} 私人依据 · ${ne.length} Notion证据</span></div>${r.when?`<div class="playbook-when"><b>什么时候用</b><span>${ew(r.when)}</span></div>`:''}<div class="playbook-core"><div class="playbook-label">我的判断规则</div><p>${ew(r.principle||r.detail||'')}</p></div><div class="playbook-columns">${arrayBlock('怎么做',r.steps)}${arrayBlock('看什么指标',r.metrics)}${arrayBlock('避免什么',r.traps)}</div>${r.tensions?.length?`<div class="system-tension"><b>⚖ 冲突 / 待验证</b>${r.tensions.map(x=>`<div>${ew(x)}</div>`).join('')}</div>`:''}<details class="playbook-evidence"><summary>查看依据：经验 / 读书 / Notion</summary><div class="evidence-sources">${se.map(n=>`<div class="system-source-note"><b>${ew(n.source_label)} · ${ew(n.section)}</b><p>${ew(n.text.length>420?n.text.slice(0,420)+'…':n.text)}</p></div>`).join('')}${ne.map(x=>`<a class="playbook-source" href="knowledge.html?open=${encodeURIComponent(x.a.id||'')}" target="_self"><span>${ew(x.a.title)}</span><small>Notion · ${ew(x.a.category||'未分类')} · 关联：${ew(x.hits.slice(0,4).join(' / '))}</small></a>`).join('')}</div></details></article>`;}).join('')||'<div class="empty"><h3>没有匹配规则</h3><p>换一个问题词，或选择“全部”。</p></div>';}
async function unlock(){try{WS=await loadWorkSystemData({prompt:true});if(WS.locked){$w('workSystemStatus').textContent='尚未生成加密 Work System，或未解锁。';return;}WK=await loadKnowledgeData({prompt:false});$w('workSystemGate').classList.add('hidden');$w('workSystemContent').classList.remove('hidden');$w('lockWorkSystem')?.classList.remove('hidden');$w('workSystemStatus').textContent=`Google同步 ${WS.meta?.snapshot_at?new Date(WS.meta.snapshot_at).toLocaleString('ja-JP'):'完成'} · ${WS.meta?.synthesis==='openai'?'已综合成规则':'规则候选模式'}`;renderMetrics();renderSources();renderChips();renderRules();}catch(e){console.error(e);$w('workSystemStatus').textContent='读取失败：'+e.message;}}
document.addEventListener('DOMContentLoaded',()=>{$w('unlockWorkSystem')?.addEventListener('click',unlock);$w('playbookSearch')?.addEventListener('input',renderRules);$w('lockWorkSystem')?.addEventListener('click',()=>lockPrivateData(true));});
